/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/members": {
    /** Members */
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
  };
  "/members/{userId}": {
    /** Member */
    get: {
      parameters: {
        path: {
          userId: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      id: string;
      name: string;
      avatar: string;
      joinedAt?: number;
    };
    Workshop: {
      id: string;
      title: string;
      description?: string;
    };
    Event: {
      id: string;
      workshopId?: string;
      theme: string;
      date: string;
      isCronTarget: boolean;
    };
    Participant: {
      id: string;
      eventId: string;
      memberId: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
